# Generated by Django 2.0.7 on 2018-09-29 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsColorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gct_id', models.UUIDField(default=uuid.UUID('828b24b5-c3b5-11e8-af92-005056c00008'))),
                ('gct_color_type', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '产品颜色类型',
                'verbose_name_plural': '产品颜色类型',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gt_id', models.UUIDField(default=uuid.UUID('828b24b4-c3b5-11e8-a11b-005056c00008'))),
                ('gt_type', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '产品类型',
                'verbose_name_plural': '产品类型',
                'ordering': ['pk'],
            },
        ),
    ]
