# Generated by Django 2.0.7 on 2018-11-01 10:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsColorMatchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcmt_id', models.UUIDField(default=uuid.UUID('b9ae91a9-dd80-11e8-ae24-005056c00008'))),
                ('gcmt_color_type', models.CharField(max_length=50)),
                ('gcmt_goods_gi', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '产品拼色类型',
                'verbose_name_plural': '产品拼色类型',
                'ordering': ['pk'],
            },
        ),
        migrations.AlterField(
            model_name='goodscolortype',
            name='gct_id',
            field=models.UUIDField(default=uuid.UUID('b9ae91a8-dd80-11e8-b04c-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='gt_id',
            field=models.UUIDField(default=uuid.UUID('b9ae6a9a-dd80-11e8-929d-005056c00008')),
        ),
    ]
