# Generated by Django 2.0.7 on 2018-11-01 14:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_type', '0002_auto_20181101_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscolormatchtype',
            name='gcmt_id',
            field=models.UUIDField(default=uuid.UUID('ddac1e8a-dda1-11e8-80fc-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscolortype',
            name='gct_id',
            field=models.UUIDField(default=uuid.UUID('ddabf779-dda1-11e8-a7c4-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='gt_id',
            field=models.UUIDField(default=uuid.UUID('ddabf778-dda1-11e8-94ea-005056c00008')),
        ),
    ]
