# Generated by Django 2.0.7 on 2018-11-01 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_type', '0003_auto_20181101_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscolormatchtype',
            name='gcmt_id',
            field=models.UUIDField(default=uuid.UUID('a509891a-dda5-11e8-b127-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscolortype',
            name='gct_id',
            field=models.UUIDField(default=uuid.UUID('a509620b-dda5-11e8-a01f-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='gt_id',
            field=models.UUIDField(default=uuid.UUID('a509620a-dda5-11e8-923d-005056c00008')),
        ),
    ]
