# Generated by Django 2.0.7 on 2018-11-02 09:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_type', '0004_auto_20181101_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscolormatchtype',
            name='gcmt_goods_gi',
        ),
        migrations.AddField(
            model_name='goodscolormatchtype',
            name='gcmt_goodscolortype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods_type.GoodsColorType'),
        ),
        migrations.AddField(
            model_name='goodscolortype',
            name='gct_color_match',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='goodscolormatchtype',
            name='gcmt_id',
            field=models.UUIDField(default=uuid.UUID('b09a38f4-de3b-11e8-8ee0-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscolortype',
            name='gct_id',
            field=models.UUIDField(default=uuid.UUID('b09a11e5-de3b-11e8-8dc1-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='gt_id',
            field=models.UUIDField(default=uuid.UUID('b09a11e4-de3b-11e8-8cf3-005056c00008')),
        ),
    ]
