# Generated by Django 2.0.7 on 2018-11-02 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_type', '0005_auto_20181102_0907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodscolormatchtype',
            name='gcmt_goodscolortype',
        ),
        migrations.RemoveField(
            model_name='goodscolortype',
            name='gct_color_match',
        ),
        migrations.AlterField(
            model_name='goodscolortype',
            name='gct_id',
            field=models.UUIDField(default=uuid.UUID('d3ee8925-de3e-11e8-9adb-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='gt_id',
            field=models.UUIDField(default=uuid.UUID('d3ee8924-de3e-11e8-8829-005056c00008')),
        ),
        migrations.DeleteModel(
            name='GoodsColorMatchType',
        ),
    ]
