# Generated by Django 2.0.7 on 2018-12-06 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_type', '0006_auto_20181102_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscolortype',
            name='gct_id',
            field=models.UUIDField(default=uuid.UUID('316bfa82-f91d-11e8-831b-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='gt_id',
            field=models.UUIDField(default=uuid.UUID('316bd374-f91d-11e8-af5e-005056c00008')),
        ),
    ]
