# Generated by Django 2.0.7 on 2019-05-15 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_type', '0007_auto_20181206_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscolortype',
            name='gct_id',
            field=models.UUIDField(default=uuid.UUID('e29ddc0b-76bb-11e9-b00c-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='gt_id',
            field=models.UUIDField(default=uuid.UUID('e29ddc0a-76bb-11e9-b8ac-005056c00008')),
        ),
    ]
