# Generated by Django 2.0.7 on 2019-07-15 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_type', '0008_auto_20190515_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscolortype',
            name='gct_id',
            field=models.UUIDField(default=uuid.UUID('bb3b0947-a6c4-11e9-8797-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodstype',
            name='gt_id',
            field=models.UUIDField(default=uuid.UUID('bb3b0946-a6c4-11e9-8c06-005056c00008')),
        ),
    ]
