# Generated by Django 2.0.7 on 2018-11-01 14:46

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_change', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscolorchange',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='goodscolorchange',
            name='gcc_id',
            field=models.UUIDField(default=uuid.UUID('ddae1a5a-dda1-11e8-b586-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscolorchangecolor',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='goodscolorchangecolor',
            name='gccc_id',
            field=models.UUIDField(default=uuid.UUID('ddae4168-dda1-11e8-87a0-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsextencechange',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='goodsextencechange',
            name='gec_id',
            field=models.UUIDField(default=uuid.UUID('ddadcc39-dda1-11e8-9220-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsorderchange',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='goodsorderchange',
            name='goc_id',
            field=models.UUIDField(default=uuid.UUID('ddadf34a-dda1-11e8-a844-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsorderchangechange',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='goodsorderchangechange',
            name='gocc_id',
            field=models.UUIDField(default=uuid.UUID('ddadf34b-dda1-11e8-97b9-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodspricechange',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='goodspricechange',
            name='gpc_id',
            field=models.UUIDField(default=uuid.UUID('ddadcc38-dda1-11e8-b874-005056c00008')),
        ),
        migrations.AlterField(
            model_name='productanalysisconfirmation',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='productanalysisconfirmation',
            name='pac_id',
            field=models.UUIDField(default=uuid.UUID('ddada528-dda1-11e8-bf2e-005056c00008')),
        ),
    ]
