# Generated by Django 2.0.7 on 2018-11-01 15:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_change', '0002_auto_20181101_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscolorchange',
            name='gcc_id',
            field=models.UUIDField(default=uuid.UUID('a50b84e9-dda5-11e8-9e5a-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscolorchangecolor',
            name='gccc_id',
            field=models.UUIDField(default=uuid.UUID('a50babf8-dda5-11e8-b3c4-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsextencechange',
            name='gec_id',
            field=models.UUIDField(default=uuid.UUID('a50b36cb-dda5-11e8-adba-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsorderchange',
            name='goc_id',
            field=models.UUIDField(default=uuid.UUID('a50b5dda-dda5-11e8-b380-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsorderchangechange',
            name='gocc_id',
            field=models.UUIDField(default=uuid.UUID('a50b84e8-dda5-11e8-9b94-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodspricechange',
            name='gpc_id',
            field=models.UUIDField(default=uuid.UUID('a50b36ca-dda5-11e8-ae9a-005056c00008')),
        ),
        migrations.AlterField(
            model_name='productanalysisconfirmation',
            name='pac_id',
            field=models.UUIDField(default=uuid.UUID('a50b0fb8-dda5-11e8-921b-005056c00008')),
        ),
    ]
