# Generated by Django 2.0.7 on 2018-12-06 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_change', '0003_auto_20181101_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscolorchange',
            name='gcc_id',
            field=models.UUIDField(default=uuid.UUID('316e4474-f91d-11e8-9a3d-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscolorchangecolor',
            name='gccc_id',
            field=models.UUIDField(default=uuid.UUID('316e4475-f91d-11e8-b320-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsextencechange',
            name='gec_id',
            field=models.UUIDField(default=uuid.UUID('316df653-f91d-11e8-9ae6-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsorderchange',
            name='goc_id',
            field=models.UUIDField(default=uuid.UUID('316e1d64-f91d-11e8-98b3-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsorderchangechange',
            name='gocc_id',
            field=models.UUIDField(default=uuid.UUID('316e1d65-f91d-11e8-bbe9-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodspricechange',
            name='gpc_id',
            field=models.UUIDField(default=uuid.UUID('316df652-f91d-11e8-84e6-005056c00008')),
        ),
        migrations.AlterField(
            model_name='productanalysisconfirmation',
            name='pac_id',
            field=models.UUIDField(default=uuid.UUID('316dcf42-f91d-11e8-bc2f-005056c00008')),
        ),
    ]
