# Generated by Django 2.0.7 on 2019-05-15 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_change', '0004_auto_20181206_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscolorchange',
            name='gcc_id',
            field=models.UUIDField(default=uuid.UUID('e2a025fb-76bb-11e9-9cd3-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscolorchangecolor',
            name='gccc_id',
            field=models.UUIDField(default=uuid.UUID('e2a04d0a-76bb-11e9-9cee-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsextencechange',
            name='gec_id',
            field=models.UUIDField(default=uuid.UUID('e29fd7db-76bb-11e9-bf26-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsorderchange',
            name='goc_id',
            field=models.UUIDField(default=uuid.UUID('e29ffee8-76bb-11e9-968c-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsorderchangechange',
            name='gocc_id',
            field=models.UUIDField(default=uuid.UUID('e2a025fa-76bb-11e9-9664-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodspricechange',
            name='gpc_id',
            field=models.UUIDField(default=uuid.UUID('e29fd7da-76bb-11e9-a401-005056c00008')),
        ),
        migrations.AlterField(
            model_name='productanalysisconfirmation',
            name='pac_id',
            field=models.UUIDField(default=uuid.UUID('e29fb0ca-76bb-11e9-93e6-005056c00008')),
        ),
    ]
