# Generated by Django 2.0.7 on 2019-07-15 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods_change', '0005_auto_20190515_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodscolorchange',
            name='gcc_id',
            field=models.UUIDField(default=uuid.UUID('bb3d2c25-a6c4-11e9-a744-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscolorchangecolor',
            name='gccc_id',
            field=models.UUIDField(default=uuid.UUID('bb3d5336-a6c4-11e9-aa8f-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsextencechange',
            name='gec_id',
            field=models.UUIDField(default=uuid.UUID('bb3d0514-a6c4-11e9-a1a3-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsorderchange',
            name='goc_id',
            field=models.UUIDField(default=uuid.UUID('bb3d0515-a6c4-11e9-b08d-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsorderchangechange',
            name='gocc_id',
            field=models.UUIDField(default=uuid.UUID('bb3d2c24-a6c4-11e9-a42e-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodspricechange',
            name='gpc_id',
            field=models.UUIDField(default=uuid.UUID('bb3cde07-a6c4-11e9-9d1b-005056c00008')),
        ),
        migrations.AlterField(
            model_name='productanalysisconfirmation',
            name='pac_id',
            field=models.UUIDField(default=uuid.UUID('bb3cde06-a6c4-11e9-b4d2-005056c00008')),
        ),
    ]
