# Generated by Django 2.0.7 on 2018-09-29 15:01

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods_type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_id', models.UUIDField(default=uuid.UUID('828b4bc3-c3b5-11e8-b7c1-005056c00008'))),
                ('b_name', models.CharField(max_length=100)),
                ('b_url', models.CharField(default='', max_length=100)),
                ('b_logo', models.ImageField(default='image/brand_logo/logo.png', upload_to='image')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BrandTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_id', models.UUIDField(default=uuid.UUID('828b72d2-c3b5-11e8-801c-005056c00008'))),
                ('bt_time', models.DateField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('bt_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Brand')),
            ],
            options={
                'verbose_name': '品牌抓取时间',
                'verbose_name_plural': '品牌抓取时间',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BrandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bt_id', models.UUIDField(default=uuid.UUID('828b4bc2-c3b5-11e8-a74a-005056c00008'))),
                ('bt_type', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '品牌类型',
                'verbose_name_plural': '品牌类型',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BrowseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bh_id', models.UUIDField(default=uuid.UUID('828c3624-c3b5-11e8-bc70-005056c00008'))),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '产品浏览历史',
                'verbose_name_plural': '产品浏览历史',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.UUIDField(default=uuid.UUID('828b72d4-c3b5-11e8-bb14-005056c00008'))),
                ('g_name', models.CharField(max_length=100)),
                ('g_title', models.CharField(default='', max_length=100)),
                ('g_price_type', models.CharField(default='$', max_length=20)),
                ('g_discount_price', models.CharField(default='0', max_length=20)),
                ('g_now_price', models.CharField(max_length=20)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('b_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Brand')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoodsCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_id', models.UUIDField(default=uuid.UUID('828c0f14-c3b5-11e8-a251-005056c00008'))),
                ('gc_collection', models.IntegerField(choices=[(0, '未收藏'), (1, '已收藏')], default=0)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('gc_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '产品收藏',
                'verbose_name_plural': '产品收藏',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoodsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gc_id', models.UUIDField(default=uuid.UUID('828c0f12-c3b5-11e8-afc6-005056c00008'))),
                ('gc_comment_time', models.DateField()),
                ('gc_comment', models.CharField(max_length=800)),
                ('gc_comment_star', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('gc_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '产品评论',
                'verbose_name_plural': '产品评论',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoodsCustomDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gcd_id', models.UUIDField(default=uuid.UUID('828c5d34-c3b5-11e8-886d-005056c00008'))),
                ('gcd_description', tinymce.models.HTMLField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('gcd_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '产品自定义描述',
                'verbose_name_plural': '产品自定义描述',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoodsDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gd_id', models.UUIDField(default=uuid.UUID('828be802-c3b5-11e8-953c-005056c00008'))),
                ('gd_detail', models.CharField(max_length=1000)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '详情',
                'verbose_name_plural': '详情',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoodsImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gimg_id', models.UUIDField(default=uuid.UUID('828be803-c3b5-11e8-a6e6-005056c00008'))),
                ('gimg_path', models.CharField(max_length=100)),
                ('gimg_url', models.CharField(max_length=200)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoodsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gi_id', models.UUIDField(default=uuid.UUID('828b99e4-c3b5-11e8-ba04-005056c00008'))),
                ('gi_model', models.CharField(default=0, max_length=100)),
                ('gi_color', models.CharField(max_length=100)),
                ('gi_order', models.IntegerField()),
                ('gi_gender', models.CharField(max_length=50)),
                ('gi_brand_goods_url', models.CharField(max_length=100)),
                ('gi_page', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('gi_color_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_type.GoodsColorType')),
                ('gi_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoodsLable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gl_id', models.UUIDField(default=uuid.UUID('828c3625-c3b5-11e8-a437-005056c00008'))),
                ('gl_lable', models.CharField(max_length=100)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('gl_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '产品标签',
                'verbose_name_plural': '产品标签',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoodsSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_id', models.UUIDField(default=uuid.UUID('828bc0f4-c3b5-11e8-9f3f-005056c00008'))),
                ('gs_size', models.CharField(max_length=20)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('gs_gi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInformation')),
            ],
            options={
                'verbose_name': '产品尺寸',
                'verbose_name_plural': '产品尺寸',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='GoodsStar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gs_id', models.UUIDField(default=uuid.UUID('828c0f13-c3b5-11e8-9fa5-005056c00008'))),
                ('gs_star', models.IntegerField(default=0)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('gs_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods')),
            ],
            options={
                'verbose_name': '产品星级',
                'verbose_name_plural': '产品星级',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.UUIDField(default=uuid.UUID('828b72d3-c3b5-11e8-bb4a-005056c00008'))),
                ('t_time', models.DateField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '数据时间',
                'verbose_name_plural': '数据时间',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='goodsimage',
            name='gimg_gi_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInformation'),
        ),
        migrations.AddField(
            model_name='goodsdetail',
            name='gd_gi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInformation'),
        ),
        migrations.AddField(
            model_name='goods',
            name='g_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Time'),
        ),
        migrations.AddField(
            model_name='goods',
            name='g_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods_type.GoodsType'),
        ),
        migrations.AddField(
            model_name='browsehistory',
            name='bh_goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods'),
        ),
        migrations.AddField(
            model_name='brand',
            name='b_bt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.BrandType'),
        ),
    ]
