# Generated by Django 2.0.7 on 2018-11-01 13:40

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20181018_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='b_id',
            field=models.UUIDField(default=uuid.UUID('ad670729-dd98-11e8-bcac-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtime',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('ad672e38-dd98-11e8-8fc1-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtype',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('ad670728-dd98-11e8-b0e7-005056c00008')),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='bh_id',
            field=models.UUIDField(default=uuid.UUID('ad67f18a-dd98-11e8-93b6-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_id',
            field=models.UUIDField(default=uuid.UUID('ad672e3a-dd98-11e8-82ff-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscollection',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('ad67ca79-dd98-11e8-bfe0-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscomment',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('ad67a369-dd98-11e8-b3eb-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscustomdescription',
            name='create_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 1, 13, 40, 44, 884802)),
        ),
        migrations.AlterField(
            model_name='goodscustomdescription',
            name='gcd_id',
            field=models.UUIDField(default=uuid.UUID('ad68189a-dd98-11e8-a0f6-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gd_id',
            field=models.UUIDField(default=uuid.UUID('ad677c5b-dd98-11e8-9bbe-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='gimg_id',
            field=models.UUIDField(default=uuid.UUID('ad67a368-dd98-11e8-98fa-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsinformation',
            name='gi_id',
            field=models.UUIDField(default=uuid.UUID('ad67554a-dd98-11e8-be24-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodslable',
            name='gl_id',
            field=models.UUIDField(default=uuid.UUID('ad67f18b-dd98-11e8-9dcf-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodssize',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('ad677c5a-dd98-11e8-a364-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsstar',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('ad67ca78-dd98-11e8-8bca-005056c00008')),
        ),
        migrations.AlterField(
            model_name='time',
            name='t_id',
            field=models.UUIDField(default=uuid.UUID('ad672e39-dd98-11e8-aafc-005056c00008')),
        ),
    ]
