# Generated by Django 2.0.7 on 2018-11-01 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20181101_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='b_id',
            field=models.UUIDField(default=uuid.UUID('61fb18b8-dd9a-11e8-8566-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtime',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('61fb18b9-dd9a-11e8-b5ab-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtype',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('61faf1a8-dd9a-11e8-96fe-005056c00008')),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='bh_id',
            field=models.UUIDField(default=uuid.UUID('61fbdc0b-dd9a-11e8-bfc0-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_id',
            field=models.UUIDField(default=uuid.UUID('61fb3fca-dd9a-11e8-b021-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscollection',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('61fbdc0a-dd9a-11e8-ad68-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscomment',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('61fbb4f8-dd9a-11e8-bcc3-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscustomdescription',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='goodscustomdescription',
            name='gcd_id',
            field=models.UUIDField(default=uuid.UUID('61fc031b-dd9a-11e8-a076-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gd_id',
            field=models.UUIDField(default=uuid.UUID('61fb8de8-dd9a-11e8-8a89-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='gimg_id',
            field=models.UUIDField(default=uuid.UUID('61fb8de9-dd9a-11e8-ad64-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsinformation',
            name='gi_id',
            field=models.UUIDField(default=uuid.UUID('61fb66da-dd9a-11e8-a8ae-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodslable',
            name='gl_id',
            field=models.UUIDField(default=uuid.UUID('61fc031a-dd9a-11e8-90a5-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodssize',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('61fb66db-dd9a-11e8-b870-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsstar',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('61fbb4f9-dd9a-11e8-9a7a-005056c00008')),
        ),
        migrations.AlterField(
            model_name='time',
            name='t_id',
            field=models.UUIDField(default=uuid.UUID('61fb18ba-dd9a-11e8-9c50-005056c00008')),
        ),
    ]
