# Generated by Django 2.0.7 on 2018-11-02 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20181101_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsMatchColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmc_id', models.UUIDField(default=uuid.UUID('5ee94d35-de3f-11e8-9d34-005056c00008'))),
                ('gmc_match_color', models.CharField(max_length=50)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '产品撞色',
                'verbose_name_plural': '产品撞色',
                'ordering': ['pk'],
            },
        ),
        migrations.AddField(
            model_name='goodsinformation',
            name='gi_match_color',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='brand',
            name='b_id',
            field=models.UUIDField(default=uuid.UUID('5ee8ff14-de3f-11e8-a261-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtime',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('5ee8ff15-de3f-11e8-a455-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtype',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('5ee8d806-de3f-11e8-878e-005056c00008')),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='bh_id',
            field=models.UUIDField(default=uuid.UUID('5ee9e974-de3f-11e8-9d26-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_id',
            field=models.UUIDField(default=uuid.UUID('5ee92625-de3f-11e8-9a30-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscollection',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('5ee9c265-de3f-11e8-a24b-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscomment',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('5ee99b55-de3f-11e8-af3c-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscustomdescription',
            name='gcd_id',
            field=models.UUIDField(default=uuid.UUID('5eea1086-de3f-11e8-a0d9-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gd_id',
            field=models.UUIDField(default=uuid.UUID('5ee97447-de3f-11e8-a864-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='gimg_id',
            field=models.UUIDField(default=uuid.UUID('5ee99b54-de3f-11e8-bc56-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsinformation',
            name='gi_id',
            field=models.UUIDField(default=uuid.UUID('5ee94d34-de3f-11e8-bf7c-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodslable',
            name='gl_id',
            field=models.UUIDField(default=uuid.UUID('5ee9e975-de3f-11e8-89dd-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodssize',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('5ee97446-de3f-11e8-acbe-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsstar',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('5ee9c264-de3f-11e8-b266-005056c00008')),
        ),
        migrations.AlterField(
            model_name='time',
            name='t_id',
            field=models.UUIDField(default=uuid.UUID('5ee92624-de3f-11e8-a26e-005056c00008')),
        ),
        migrations.AddField(
            model_name='goodsmatchcolor',
            name='gmc_goodsinformation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsInformation'),
        ),
    ]
