# Generated by Django 2.0.7 on 2018-12-06 14:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20181102_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandGoodsColorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgct_id', models.UUIDField(default=uuid.UUID('316d3303-f91d-11e8-87c7-005056c00008'))),
                ('bgct_goods_color', models.CharField(max_length=100)),
                ('bgct_goods_color_type', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '品牌产品颜色类型',
                'verbose_name_plural': '品牌产品颜色类型',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BrandGoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgt_id', models.UUIDField(default=uuid.UUID('316d3302-f91d-11e8-b203-005056c00008'))),
                ('bgt_goods_name', models.CharField(max_length=100)),
                ('bgt_goods_type', models.CharField(max_length=50)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '品牌产品类型',
                'verbose_name_plural': '品牌产品类型',
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveField(
            model_name='goodsmatchcolor',
            name='gmc_goodsinformation',
        ),
        migrations.AlterField(
            model_name='brand',
            name='b_id',
            field=models.UUIDField(default=uuid.UUID('316c6fb4-f91d-11e8-9021-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtime',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('316c6fb5-f91d-11e8-84ff-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtype',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('316c48a4-f91d-11e8-bdec-005056c00008')),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='bh_id',
            field=models.UUIDField(default=uuid.UUID('316d8124-f91d-11e8-94b1-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_id',
            field=models.UUIDField(default=uuid.UUID('316c96c3-f91d-11e8-b603-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscollection',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('316d5a12-f91d-11e8-a01e-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscomment',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('316d0bf5-f91d-11e8-a5d7-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscustomdescription',
            name='gcd_id',
            field=models.UUIDField(default=uuid.UUID('316d8126-f91d-11e8-987f-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gd_id',
            field=models.UUIDField(default=uuid.UUID('316ce4e5-f91d-11e8-8311-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='gimg_id',
            field=models.UUIDField(default=uuid.UUID('316d0bf4-f91d-11e8-b7e2-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsinformation',
            name='gi_id',
            field=models.UUIDField(default=uuid.UUID('316cbdd2-f91d-11e8-a6d0-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodslable',
            name='gl_id',
            field=models.UUIDField(default=uuid.UUID('316d8125-f91d-11e8-aa4d-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodssize',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('316ce4e4-f91d-11e8-bcd3-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsstar',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('316d3304-f91d-11e8-9b32-005056c00008')),
        ),
        migrations.AlterField(
            model_name='time',
            name='t_id',
            field=models.UUIDField(default=uuid.UUID('316c96c2-f91d-11e8-b5e5-005056c00008')),
        ),
        migrations.DeleteModel(
            name='GoodsMatchColor',
        ),
        migrations.AddField(
            model_name='brandgoodstype',
            name='bgt_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Brand'),
        ),
        migrations.AddField(
            model_name='brandgoodscolortype',
            name='bgct_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Brand'),
        ),
    ]
