# Generated by Django 2.0.7 on 2019-03-13 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20181206_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='b_id',
            field=models.UUIDField(default=uuid.UUID('4535e469-4555-11e9-8181-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandgoodscolortype',
            name='bgct_id',
            field=models.UUIDField(default=uuid.UUID('4536a7b5-4555-11e9-b44d-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandgoodstype',
            name='bgt_id',
            field=models.UUIDField(default=uuid.UUID('4536a7b4-4555-11e9-981a-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtime',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('45360b76-4555-11e9-b81d-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtype',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('4535e468-4555-11e9-90a2-005056c00008')),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='bh_id',
            field=models.UUIDField(default=uuid.UUID('4536f5d2-4555-11e9-a90d-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_id',
            field=models.UUIDField(default=uuid.UUID('45363286-4555-11e9-88e6-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscollection',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('4536cec3-4555-11e9-b423-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscomment',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('453680a5-4555-11e9-a8b7-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscustomdescription',
            name='gcd_id',
            field=models.UUIDField(default=uuid.UUID('45371ce2-4555-11e9-bdf8-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gd_id',
            field=models.UUIDField(default=uuid.UUID('45365995-4555-11e9-a484-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='gimg_id',
            field=models.UUIDField(default=uuid.UUID('453680a4-4555-11e9-8454-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsinformation',
            name='gi_brand_goods_url',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='goodsinformation',
            name='gi_id',
            field=models.UUIDField(default=uuid.UUID('45363287-4555-11e9-be6c-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodslable',
            name='gl_id',
            field=models.UUIDField(default=uuid.UUID('4536f5d3-4555-11e9-b939-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodssize',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('45365994-4555-11e9-899c-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsstar',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('4536cec2-4555-11e9-a5dd-005056c00008')),
        ),
        migrations.AlterField(
            model_name='time',
            name='t_id',
            field=models.UUIDField(default=uuid.UUID('45360b77-4555-11e9-b260-005056c00008')),
        ),
    ]
