# Generated by Django 2.0.7 on 2019-03-20 10:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_auto_20190313_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='b_id',
            field=models.UUIDField(default=uuid.UUID('1a157c19-4ab7-11e9-a124-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandgoodscolortype',
            name='bgct_id',
            field=models.UUIDField(default=uuid.UUID('1a166677-4ab7-11e9-af44-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandgoodstype',
            name='bgt_id',
            field=models.UUIDField(default=uuid.UUID('1a166676-4ab7-11e9-b94f-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtime',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('1a15a326-4ab7-11e9-be9a-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtype',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('1a157c18-4ab7-11e9-b24b-005056c00008')),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='bh_id',
            field=models.UUIDField(default=uuid.UUID('1a16b499-4ab7-11e9-8c30-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_id',
            field=models.UUIDField(default=uuid.UUID('1a15ca36-4ab7-11e9-8a9b-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscollection',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('1a16b498-4ab7-11e9-8ec7-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscomment',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('1a163f67-4ab7-11e9-99c9-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscustomdescription',
            name='gcd_id',
            field=models.UUIDField(default=uuid.UUID('1a1702b6-4ab7-11e9-a7f2-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gd_id',
            field=models.UUIDField(default=uuid.UUID('1a161859-4ab7-11e9-a52f-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='gimg_id',
            field=models.UUIDField(default=uuid.UUID('1a163f66-4ab7-11e9-8b74-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsinformation',
            name='gi_brand_goods_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsinformation',
            name='gi_id',
            field=models.UUIDField(default=uuid.UUID('1a15f148-4ab7-11e9-84d1-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodslable',
            name='gl_id',
            field=models.UUIDField(default=uuid.UUID('1a16dba6-4ab7-11e9-bfd5-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodssize',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('1a161858-4ab7-11e9-bb6d-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsstar',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('1a168d88-4ab7-11e9-9545-005056c00008')),
        ),
        migrations.AlterField(
            model_name='time',
            name='t_id',
            field=models.UUIDField(default=uuid.UUID('1a15a327-4ab7-11e9-87ed-005056c00008')),
        ),
    ]
