# Generated by Django 2.0.7 on 2019-05-15 10:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20190320_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='b_id',
            field=models.UUIDField(default=uuid.UUID('e29e513b-76bb-11e9-a7c2-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandgoodscolortype',
            name='bgct_id',
            field=models.UUIDField(default=uuid.UUID('e29f148b-76bb-11e9-b383-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandgoodstype',
            name='bgt_id',
            field=models.UUIDField(default=uuid.UUID('e29f148a-76bb-11e9-809f-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtime',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('e29e784a-76bb-11e9-b007-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtype',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('e29e513a-76bb-11e9-8dfd-005056c00008')),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='bh_id',
            field=models.UUIDField(default=uuid.UUID('e29f62a8-76bb-11e9-8a61-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_id',
            field=models.UUIDField(default=uuid.UUID('e29e9f5a-76bb-11e9-b976-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscollection',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('e29f3b9b-76bb-11e9-a728-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscomment',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('e29eed7b-76bb-11e9-8172-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscustomdescription',
            name='gcd_id',
            field=models.UUIDField(default=uuid.UUID('e29f89ba-76bb-11e9-adce-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gd_id',
            field=models.UUIDField(default=uuid.UUID('e29ec669-76bb-11e9-982b-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='gimg_id',
            field=models.UUIDField(default=uuid.UUID('e29eed7a-76bb-11e9-9b77-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='gimg_url',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='goodsinformation',
            name='gi_id',
            field=models.UUIDField(default=uuid.UUID('e29e9f5b-76bb-11e9-9451-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodslable',
            name='gl_id',
            field=models.UUIDField(default=uuid.UUID('e29f62a9-76bb-11e9-b898-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodssize',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('e29ec668-76bb-11e9-8e98-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsstar',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('e29f3b9a-76bb-11e9-b739-005056c00008')),
        ),
        migrations.AlterField(
            model_name='time',
            name='t_id',
            field=models.UUIDField(default=uuid.UUID('e29e784b-76bb-11e9-bff0-005056c00008')),
        ),
    ]
