# Generated by Django 2.0.7 on 2019-07-15 13:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_auto_20190515_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='g_goods_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='b_id',
            field=models.UUIDField(default=uuid.UUID('bb3b7e77-a6c4-11e9-9cc7-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandgoodscolortype',
            name='bgct_id',
            field=models.UUIDField(default=uuid.UUID('bb3c41c6-a6c4-11e9-abe0-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandgoodstype',
            name='bgt_id',
            field=models.UUIDField(default=uuid.UUID('bb3c1ab7-a6c4-11e9-9f16-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtime',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('bb3b7e78-a6c4-11e9-be16-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtype',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('bb3b7e76-a6c4-11e9-b5a9-005056c00008')),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='bh_id',
            field=models.UUIDField(default=uuid.UUID('bb3c68d5-a6c4-11e9-9be0-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_id',
            field=models.UUIDField(default=uuid.UUID('bb3ba587-a6c4-11e9-b133-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscollection',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('bb3c68d4-a6c4-11e9-8fbf-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscomment',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('bb3c1ab6-a6c4-11e9-beae-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscustomdescription',
            name='gcd_id',
            field=models.UUIDField(default=uuid.UUID('bb3c8fe5-a6c4-11e9-896b-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gd_id',
            field=models.UUIDField(default=uuid.UUID('bb3bf3a5-a6c4-11e9-bba1-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='gimg_id',
            field=models.UUIDField(default=uuid.UUID('bb3bf3a6-a6c4-11e9-97c8-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsinformation',
            name='gi_id',
            field=models.UUIDField(default=uuid.UUID('bb3bcc94-a6c4-11e9-bc89-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodslable',
            name='gl_id',
            field=models.UUIDField(default=uuid.UUID('bb3c8fe4-a6c4-11e9-a8d6-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodssize',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('bb3bf3a4-a6c4-11e9-8120-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsstar',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('bb3c41c7-a6c4-11e9-98c2-005056c00008')),
        ),
        migrations.AlterField(
            model_name='time',
            name='t_id',
            field=models.UUIDField(default=uuid.UUID('bb3ba586-a6c4-11e9-b0d5-005056c00008')),
        ),
    ]
