# Generated by Django 2.0.7 on 2019-07-15 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20190715_1352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandtime',
            options={'ordering': ['-pk'], 'verbose_name': '品牌抓取时间', 'verbose_name_plural': '品牌抓取时间'},
        ),
        migrations.AlterField(
            model_name='brand',
            name='b_id',
            field=models.UUIDField(default=uuid.UUID('7f75a577-a6c7-11e9-84f7-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandgoodscolortype',
            name='bgct_id',
            field=models.UUIDField(default=uuid.UUID('7f7668c7-a6c7-11e9-aca3-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandgoodstype',
            name='bgt_id',
            field=models.UUIDField(default=uuid.UUID('7f7668c6-a6c7-11e9-8d2b-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtime',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('7f75cc86-a6c7-11e9-afbc-005056c00008')),
        ),
        migrations.AlterField(
            model_name='brandtype',
            name='bt_id',
            field=models.UUIDField(default=uuid.UUID('7f75a576-a6c7-11e9-883c-005056c00008')),
        ),
        migrations.AlterField(
            model_name='browsehistory',
            name='bh_id',
            field=models.UUIDField(default=uuid.UUID('7f76b6e4-a6c7-11e9-a5f7-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goods',
            name='g_id',
            field=models.UUIDField(default=uuid.UUID('7f75cc88-a6c7-11e9-a212-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscollection',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('7f768fd5-a6c7-11e9-be25-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscomment',
            name='gc_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodscomment',
            name='gc_id',
            field=models.UUIDField(default=uuid.UUID('7f7641b7-a6c7-11e9-bacc-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodscustomdescription',
            name='gcd_id',
            field=models.UUIDField(default=uuid.UUID('7f76ddf6-a6c7-11e9-86e9-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsdetail',
            name='gd_id',
            field=models.UUIDField(default=uuid.UUID('7f761aa5-a6c7-11e9-b46b-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsimage',
            name='gimg_id',
            field=models.UUIDField(default=uuid.UUID('7f7641b6-a6c7-11e9-8229-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsinformation',
            name='gi_id',
            field=models.UUIDField(default=uuid.UUID('7f75f394-a6c7-11e9-ba95-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodslable',
            name='gl_id',
            field=models.UUIDField(default=uuid.UUID('7f76b6e5-a6c7-11e9-839a-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodssize',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('7f761aa4-a6c7-11e9-b91d-005056c00008')),
        ),
        migrations.AlterField(
            model_name='goodsstar',
            name='gs_id',
            field=models.UUIDField(default=uuid.UUID('7f768fd4-a6c7-11e9-a15b-005056c00008')),
        ),
        migrations.AlterField(
            model_name='time',
            name='t_id',
            field=models.UUIDField(default=uuid.UUID('7f75cc87-a6c7-11e9-8d60-005056c00008')),
        ),
    ]
