# Generated by Django 2.0.7 on 2018-10-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.UUIDField()),
                ('u_login_name', models.CharField(max_length=100)),
                ('u_password', models.CharField(max_length=100)),
                ('u_username', models.CharField(max_length=100)),
                ('u_phone_number', models.CharField(max_length=100)),
                ('u_email', models.EmailField(max_length=254)),
                ('u_gen_time', models.DateField(auto_now_add=True)),
                ('u_last_login_time', models.DateField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UserLoginTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ult_id', models.UUIDField()),
                ('ult_login_time', models.DateField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('create_end_date', models.DateField(auto_now=True)),
                ('isdelete', models.BooleanField(default=False)),
                ('ult_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'verbose_name': '用户历史登陆时间',
                'verbose_name_plural': '用户历史登陆时间',
                'ordering': ['pk'],
            },
        ),
    ]
