# Generated by Django 2.0.7 on 2018-10-16 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_last_login_ip',
            field=models.CharField(default='127.0.0.1', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='u_reg_ip',
            field=models.CharField(default='127.0.0.1', max_length=100),
        ),
        migrations.AddField(
            model_name='userlogintime',
            name='ult_login_ip',
            field=models.CharField(default='127.0.0.1', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_last_login_time',
            field=models.DateField(default=datetime.datetime(1900, 1, 1, 0, 0)),
        ),
    ]
