# Generated by Django 2.0.7 on 2018-10-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20181016_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='u_last_login_ip',
            field=models.CharField(default='0.0.0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_reg_ip',
            field=models.CharField(default='0.0.0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='userlogintime',
            name='ult_login_ip',
            field=models.CharField(default='0.0.0.0', max_length=100),
        ),
    ]
